#!/bin/bash
# assign variables

ACTION=${1}
version=1.0.1
function show_version() {
$version
}
function delete_file() {
rm "${1}-12345"
}
function create_file() {
touch "${1}-12345"
}
function display_help() {
cat << EOF
Usage: ${0} {-v|--version|-d|--delete|-c|--create|-h|--help} <filename>
OPTIONS:
	-v | --version	Display the version
	-d | --delete	Delete a file
	-c | --create	Create a new file
	-h | --help	Display the command help
Examples:
	Display the version:
		$ ${0} -v foo.txt
	Delete a file:
		$ ${0} -d foo.txt
	Create a new file:
		$ ${0} -c foo.txt
	Display help:
		$ ${0} -h
EOF
}

case "$ACTION" in
	-h| --help)
		display_help
		;;
	-c| --create)
		create_file "${2:-server}"
		;;
	-d| --delete)
		delete_file "${2:-server}"
		;;
	-v| --version)
		show_version
		;;
	*)
	echo "Usage ${0} {-v|-d|-c|-h}"
	exit 1
esac
